package com.example.mall.entity;

import java.io.Serializable;

public class GoodsSku implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.goodsid
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.inventoryCount
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Integer inventorycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.price
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Float price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_sku.pic
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.id
     *
     * @return the value of goods_sku.id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.id
     *
     * @param id the value for goods_sku.id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.spec
     *
     * @return the value of goods_sku.spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.spec
     *
     * @param spec the value for goods_sku.spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.goodsid
     *
     * @return the value of goods_sku.goodsid
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.goodsid
     *
     * @param goodsid the value for goods_sku.goodsid
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.inventoryCount
     *
     * @return the value of goods_sku.inventoryCount
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Integer getInventorycount() {
        return inventorycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.inventoryCount
     *
     * @param inventorycount the value for goods_sku.inventoryCount
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setInventorycount(Integer inventorycount) {
        this.inventorycount = inventorycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.price
     *
     * @return the value of goods_sku.price
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.price
     *
     * @param price the value for goods_sku.price
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_sku.pic
     *
     * @return the value of goods_sku.pic
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_sku.pic
     *
     * @param pic the value for goods_sku.pic
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setPic(String pic) {
        this.pic = pic;
    }
}