package com.example.mall.entity;

import java.util.ArrayList;
import java.util.List;

public class GoodsSpecExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public GoodsSpecExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNull() {
            addCriterion("goodsid is null");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNotNull() {
            addCriterion("goodsid is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsidEqualTo(Integer value) {
            addCriterion("goodsid =", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotEqualTo(Integer value) {
            addCriterion("goodsid <>", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThan(Integer value) {
            addCriterion("goodsid >", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsid >=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThan(Integer value) {
            addCriterion("goodsid <", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThanOrEqualTo(Integer value) {
            addCriterion("goodsid <=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidIn(List<Integer> values) {
            addCriterion("goodsid in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotIn(List<Integer> values) {
            addCriterion("goodsid not in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidBetween(Integer value1, Integer value2) {
            addCriterion("goodsid between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsid not between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andSpecnameIsNull() {
            addCriterion("specName is null");
            return (Criteria) this;
        }

        public Criteria andSpecnameIsNotNull() {
            addCriterion("specName is not null");
            return (Criteria) this;
        }

        public Criteria andSpecnameEqualTo(String value) {
            addCriterion("specName =", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameNotEqualTo(String value) {
            addCriterion("specName <>", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameGreaterThan(String value) {
            addCriterion("specName >", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameGreaterThanOrEqualTo(String value) {
            addCriterion("specName >=", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameLessThan(String value) {
            addCriterion("specName <", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameLessThanOrEqualTo(String value) {
            addCriterion("specName <=", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameLike(String value) {
            addCriterion("specName like", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameNotLike(String value) {
            addCriterion("specName not like", value, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameIn(List<String> values) {
            addCriterion("specName in", values, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameNotIn(List<String> values) {
            addCriterion("specName not in", values, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameBetween(String value1, String value2) {
            addCriterion("specName between", value1, value2, "specname");
            return (Criteria) this;
        }

        public Criteria andSpecnameNotBetween(String value1, String value2) {
            addCriterion("specName not between", value1, value2, "specname");
            return (Criteria) this;
        }

        public Criteria andSpervalueIsNull() {
            addCriterion("sperValue is null");
            return (Criteria) this;
        }

        public Criteria andSpervalueIsNotNull() {
            addCriterion("sperValue is not null");
            return (Criteria) this;
        }

        public Criteria andSpervalueEqualTo(String value) {
            addCriterion("sperValue =", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueNotEqualTo(String value) {
            addCriterion("sperValue <>", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueGreaterThan(String value) {
            addCriterion("sperValue >", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueGreaterThanOrEqualTo(String value) {
            addCriterion("sperValue >=", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueLessThan(String value) {
            addCriterion("sperValue <", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueLessThanOrEqualTo(String value) {
            addCriterion("sperValue <=", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueLike(String value) {
            addCriterion("sperValue like", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueNotLike(String value) {
            addCriterion("sperValue not like", value, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueIn(List<String> values) {
            addCriterion("sperValue in", values, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueNotIn(List<String> values) {
            addCriterion("sperValue not in", values, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueBetween(String value1, String value2) {
            addCriterion("sperValue between", value1, value2, "spervalue");
            return (Criteria) this;
        }

        public Criteria andSpervalueNotBetween(String value1, String value2) {
            addCriterion("sperValue not between", value1, value2, "spervalue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_spec
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 21 15:21:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}