package com.example.mall.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class OmsOrderItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.item_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.order_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.order_sn
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_pic
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private String productPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_name
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_brand
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private String productBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_price
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_quantity
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Integer productQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_sku_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private Long productSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order_item.product_attr
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private String productAttr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order_item
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.item_id
     *
     * @return the value of oms_order_item.item_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.item_id
     *
     * @param itemId the value for oms_order_item.item_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.order_id
     *
     * @return the value of oms_order_item.order_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.order_id
     *
     * @param orderId the value for oms_order_item.order_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.order_sn
     *
     * @return the value of oms_order_item.order_sn
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.order_sn
     *
     * @param orderSn the value for oms_order_item.order_sn
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_id
     *
     * @return the value of oms_order_item.product_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_id
     *
     * @param productId the value for oms_order_item.product_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_pic
     *
     * @return the value of oms_order_item.product_pic
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getProductPic() {
        return productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_pic
     *
     * @param productPic the value for oms_order_item.product_pic
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductPic(String productPic) {
        this.productPic = productPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_name
     *
     * @return the value of oms_order_item.product_name
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_name
     *
     * @param productName the value for oms_order_item.product_name
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_brand
     *
     * @return the value of oms_order_item.product_brand
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getProductBrand() {
        return productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_brand
     *
     * @param productBrand the value for oms_order_item.product_brand
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductBrand(String productBrand) {
        this.productBrand = productBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_price
     *
     * @return the value of oms_order_item.product_price
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_price
     *
     * @param productPrice the value for oms_order_item.product_price
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_quantity
     *
     * @return the value of oms_order_item.product_quantity
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Integer getProductQuantity() {
        return productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_quantity
     *
     * @param productQuantity the value for oms_order_item.product_quantity
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductQuantity(Integer productQuantity) {
        this.productQuantity = productQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_sku_id
     *
     * @return the value of oms_order_item.product_sku_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_sku_id
     *
     * @param productSkuId the value for oms_order_item.product_sku_id
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order_item.product_attr
     *
     * @return the value of oms_order_item.product_attr
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public String getProductAttr() {
        return productAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order_item.product_attr
     *
     * @param productAttr the value for oms_order_item.product_attr
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    public void setProductAttr(String productAttr) {
        this.productAttr = productAttr;
    }
}