package com.example.mall.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Shoppingcar implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.goodsid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.id
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.image
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.name
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.num
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.price
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.stroeid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private Integer stroeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.stroename
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private String stroename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingcar.userid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.goodsid
     *
     * @return the value of shoppingcar.goodsid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.goodsid
     *
     * @param goodsid the value for shoppingcar.goodsid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.id
     *
     * @return the value of shoppingcar.id
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.id
     *
     * @param id the value for shoppingcar.id
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.image
     *
     * @return the value of shoppingcar.image
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.image
     *
     * @param image the value for shoppingcar.image
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.name
     *
     * @return the value of shoppingcar.name
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.name
     *
     * @param name the value for shoppingcar.name
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.num
     *
     * @return the value of shoppingcar.num
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.num
     *
     * @param num the value for shoppingcar.num
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.price
     *
     * @return the value of shoppingcar.price
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.price
     *
     * @param price the value for shoppingcar.price
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.stroeid
     *
     * @return the value of shoppingcar.stroeid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public Integer getStroeid() {
        return stroeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.stroeid
     *
     * @param stroeid the value for shoppingcar.stroeid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setStroeid(Integer stroeid) {
        this.stroeid = stroeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.stroename
     *
     * @return the value of shoppingcar.stroename
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public String getStroename() {
        return stroename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.stroename
     *
     * @param stroename the value for shoppingcar.stroename
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setStroename(String stroename) {
        this.stroename = stroename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingcar.userid
     *
     * @return the value of shoppingcar.userid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingcar.userid
     *
     * @param userid the value for shoppingcar.userid
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}