package com.example.mall.mapper;

import com.example.mall.entity.Discuss;
import com.example.mall.entity.DiscussExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
@Mapper
public interface DiscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @SelectProvider(type=DiscussSqlProvider.class, method="countByExample")
    long countByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @DeleteProvider(type=DiscussSqlProvider.class, method="deleteByExample")
    int deleteByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @Delete({
        "delete from discuss",
        "where discussid = #{discussid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer discussid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @Insert({
        "insert into discuss (discussid, userid, ",
        "goodsid, content, ",
        "grade)",
        "values (#{discussid,jdbcType=INTEGER}, #{userid,jdbcType=INTEGER}, ",
        "#{goodsid,jdbcType=INTEGER}, #{content,jdbcType=VARCHAR}, ",
        "#{grade,jdbcType=INTEGER})"
    })
    int insert(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @InsertProvider(type=DiscussSqlProvider.class, method="insertSelective")
    int insertSelective(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @SelectProvider(type=DiscussSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="discussid", property="discussid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="grade", property="grade", jdbcType=JdbcType.INTEGER)
    })
    List<Discuss> selectByExample(DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @Select({
        "select",
        "discussid, userid, goodsid, content, grade",
        "from discuss",
        "where discussid = #{discussid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="discussid", property="discussid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="grade", property="grade", jdbcType=JdbcType.INTEGER)
    })
    Discuss selectByPrimaryKey(Integer discussid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @UpdateProvider(type=DiscussSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Discuss record, @Param("example") DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @UpdateProvider(type=DiscussSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Discuss record, @Param("example") DiscussExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @UpdateProvider(type=DiscussSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Discuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Dec 10 17:29:53 CST 2019
     */
    @Update({
        "update discuss",
        "set userid = #{userid,jdbcType=INTEGER},",
          "goodsid = #{goodsid,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "grade = #{grade,jdbcType=INTEGER}",
        "where discussid = #{discussid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Discuss record);
}