package com.example.mall.mapper;

import com.example.mall.entity.GoodsSku;
import com.example.mall.entity.GoodsSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GoodsSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @SelectProvider(type=GoodsSkuSqlProvider.class, method="countByExample")
    long countByExample(GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @DeleteProvider(type=GoodsSkuSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @Insert({
        "insert into goods_sku (sp, goodsid, ",
        "stock, price, pic)",
        "values (#{sp,jdbcType=VARCHAR}, #{goodsid,jdbcType=INTEGER}, ",
        "#{stock,jdbcType=INTEGER}, #{price,jdbcType=REAL}, #{pic,jdbcType=VARCHAR})"
    })
    int insert(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @InsertProvider(type=GoodsSkuSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @SelectProvider(type=GoodsSkuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="sp", property="sp", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER),
        @Result(column="stock", property="stock", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.REAL),
        @Result(column="pic", property="pic", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsSku> selectByExample(GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsSku record, @Param("example") GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsSku record, @Param("example") GoodsSkuExample example);
}