package com.example.mall.mapper;

import com.example.mall.entity.GoodsSku;
import com.example.mall.entity.GoodsSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GoodsSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @SelectProvider(type=GoodsSkuSqlProvider.class, method="countByExample")
    long countByExample(GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @DeleteProvider(type=GoodsSkuSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Delete({
        "delete from goods_sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Insert({
        "insert into goods_sku (id, spec, ",
        "goodsid, inventoryCount, ",
        "price, pic)",
        "values (#{id,jdbcType=INTEGER}, #{spec,jdbcType=VARCHAR}, ",
        "#{goodsid,jdbcType=INTEGER}, #{inventorycount,jdbcType=INTEGER}, ",
        "#{price,jdbcType=REAL}, #{pic,jdbcType=VARCHAR})"
    })
    int insert(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @InsertProvider(type=GoodsSkuSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @SelectProvider(type=GoodsSkuSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spec", property="spec", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER),
        @Result(column="inventoryCount", property="inventorycount", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.REAL),
        @Result(column="pic", property="pic", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsSku> selectByExample(GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Select({
        "select",
        "id, spec, goodsid, inventoryCount, price, pic",
        "from goods_sku",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="spec", property="spec", jdbcType=JdbcType.VARCHAR),
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER),
        @Result(column="inventoryCount", property="inventorycount", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.REAL),
        @Result(column="pic", property="pic", jdbcType=JdbcType.VARCHAR)
    })
    GoodsSku selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsSku record, @Param("example") GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsSku record, @Param("example") GoodsSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @UpdateProvider(type=GoodsSkuSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_sku
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Update({
        "update goods_sku",
        "set spec = #{spec,jdbcType=VARCHAR},",
          "goodsid = #{goodsid,jdbcType=INTEGER},",
          "inventoryCount = #{inventorycount,jdbcType=INTEGER},",
          "price = #{price,jdbcType=REAL},",
          "pic = #{pic,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GoodsSku record);
}