package com.example.mall.mapper;

import com.example.mall.entity.GoodsSpec;
import com.example.mall.entity.GoodsSpecExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface GoodsSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @SelectProvider(type=GoodsSpecSqlProvider.class, method="countByExample")
    long countByExample(GoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @DeleteProvider(type=GoodsSpecSqlProvider.class, method="deleteByExample")
    int deleteByExample(GoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Delete({
        "delete from goods_spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Insert({
        "insert into goods_spec (id, goodsid, ",
        "specName, sperValue)",
        "values (#{id,jdbcType=INTEGER}, #{goodsid,jdbcType=INTEGER}, ",
        "#{specname,jdbcType=VARCHAR}, #{spervalue,jdbcType=VARCHAR})"
    })
    int insert(GoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @InsertProvider(type=GoodsSpecSqlProvider.class, method="insertSelective")
    int insertSelective(GoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @SelectProvider(type=GoodsSpecSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER),
        @Result(column="specName", property="specname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sperValue", property="spervalue", jdbcType=JdbcType.VARCHAR)
    })
    List<GoodsSpec> selectByExample(GoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Select({
        "select",
        "id, goodsid, specName, sperValue",
        "from goods_spec",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER),
        @Result(column="specName", property="specname", jdbcType=JdbcType.VARCHAR),
        @Result(column="sperValue", property="spervalue", jdbcType=JdbcType.VARCHAR)
    })
    GoodsSpec selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @UpdateProvider(type=GoodsSpecSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") GoodsSpec record, @Param("example") GoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @UpdateProvider(type=GoodsSpecSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") GoodsSpec record, @Param("example") GoodsSpecExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @UpdateProvider(type=GoodsSpecSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(GoodsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_spec
     *
     * @mbg.generated Tue Jan 21 15:21:21 CST 2020
     */
    @Update({
        "update goods_spec",
        "set goodsid = #{goodsid,jdbcType=INTEGER},",
          "specName = #{specname,jdbcType=VARCHAR},",
          "sperValue = #{spervalue,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GoodsSpec record);
}