package com.example.mall.mapper;

import com.example.mall.entity.Shoppingcar;
import com.example.mall.entity.ShoppingcarExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ShoppingcarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @SelectProvider(type=ShoppingcarSqlProvider.class, method="countByExample")
    long countByExample(ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @DeleteProvider(type=ShoppingcarSqlProvider.class, method="deleteByExample")
    int deleteByExample(ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @Delete({
        "delete from shoppingcar",
        "where goodsid = #{goodsid,jdbcType=INTEGER}",
          "and id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(@Param("goodsid") Integer goodsid, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @Insert({
        "insert into shoppingcar (goodsid, id, ",
        "image, name, num, ",
        "price, stroeid, ",
        "stroename, userid)",
        "values (#{goodsid,jdbcType=INTEGER}, #{id,jdbcType=INTEGER}, ",
        "#{image,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, #{num,jdbcType=INTEGER}, ",
        "#{price,jdbcType=DECIMAL}, #{stroeid,jdbcType=INTEGER}, ",
        "#{stroename,jdbcType=VARCHAR}, #{userid,jdbcType=INTEGER})"
    })
    int insert(Shoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @InsertProvider(type=ShoppingcarSqlProvider.class, method="insertSelective")
    int insertSelective(Shoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @SelectProvider(type=ShoppingcarSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="stroeid", property="stroeid", jdbcType=JdbcType.INTEGER),
        @Result(column="stroename", property="stroename", jdbcType=JdbcType.VARCHAR),
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER)
    })
    List<Shoppingcar> selectByExample(ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @Select({
        "select",
        "goodsid, id, image, name, num, price, stroeid, stroename, userid",
        "from shoppingcar",
        "where goodsid = #{goodsid,jdbcType=INTEGER}",
          "and id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="goodsid", property="goodsid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="num", property="num", jdbcType=JdbcType.INTEGER),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="stroeid", property="stroeid", jdbcType=JdbcType.INTEGER),
        @Result(column="stroename", property="stroename", jdbcType=JdbcType.VARCHAR),
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER)
    })
    Shoppingcar selectByPrimaryKey(@Param("goodsid") Integer goodsid, @Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @UpdateProvider(type=ShoppingcarSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Shoppingcar record, @Param("example") ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @UpdateProvider(type=ShoppingcarSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Shoppingcar record, @Param("example") ShoppingcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @UpdateProvider(type=ShoppingcarSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Shoppingcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingcar
     *
     * @mbg.generated Sat Jan 04 09:54:05 CST 2020
     */
    @Update({
        "update shoppingcar",
        "set image = #{image,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "num = #{num,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL},",
          "stroeid = #{stroeid,jdbcType=INTEGER},",
          "stroename = #{stroename,jdbcType=VARCHAR},",
          "userid = #{userid,jdbcType=INTEGER}",
        "where goodsid = #{goodsid,jdbcType=INTEGER}",
          "and id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Shoppingcar record);
}